# Generated by Django 2.2.16 on 2021-08-15 10:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210813_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='正文：', verbose_name='内容'),
        ),
    ]
